window.reelyCatalog = [
  {
    title: "Move Aside! I'm the Final Boss",
    genre: 'CEO / Secret Identity / Romance',
    tagline: 'Hidden king. Brutal breakup. Maximum revenge payoff.',
    poster: 'https://i.ytimg.com/vi/0SKOObeuGuA/hqdefault.jpg',
    badge: 'Top 1',
    rating: '5.0',
  },
  {
    title: 'The Double Life of My Billionaire Husband',
    genre: 'Billionaire Romance / Secret Identity',
    tagline: 'Marriage, money, and a secret nobody sees coming.',
    poster: 'https://i.ytimg.com/vi/6sFwVGMFA6I/hqdefault.jpg',
    badge: 'Hot',
    rating: '4.9',
  },
  {
    title: "Don't Miss Me When I'm Gone",
    genre: 'Heartbreak / Revenge / Second Chances',
    tagline: 'The breakup lands first. The regret lands harder.',
    poster: 'https://i.ytimg.com/vi/EiYYHh_KjMQ/hqdefault.jpg',
    badge: 'Trending',
    rating: '4.8',
  },
  {
    title: "The Cursed Alpha's Mate",
    genre: 'Paranormal / Werewolf Romance / Fantasy',
    tagline: 'A cursed alpha, a mate bond, and dangerous chemistry.',
    poster: 'https://i.ytimg.com/vi/7y1K7e5ejsk/hqdefault.jpg',
    badge: 'Fantasy',
    rating: '4.8',
  },
  {
    title: 'Bound by Vendetta: Sleeping with the Enemy',
    genre: 'Mafia Boss / Enemies-to-Lovers',
    tagline: 'Crime families, revenge, and forbidden attraction.',
    poster: 'https://i.ytimg.com/vi/ZZbWUm7u5J0/hqdefault.jpg',
    badge: 'Mafia',
    rating: '4.7',
  },
  {
    title: 'How to Tame a Silver Fox',
    genre: 'Age-Gap / Forbidden Romance',
    tagline: 'A college game turns into a messy obsession.',
    poster: 'https://i.ytimg.com/vi/cS3TKI7f4nw/hqdefault.jpg',
    badge: 'Forbidden',
    rating: '4.7',
  },
  {
    title: 'Undercover Prison King',
    genre: 'Action / Thriller / Undercover',
    tagline: 'He owns the prison. Nobody knows he is inside it.',
    poster: 'https://i.ytimg.com/vi/3yWPJFFD0-I/hqdefault.jpg',
    badge: 'Action',
    rating: '4.7',
  },
  {
    title: 'Love at Dangerous Speeds',
    genre: 'Street Racing / Romance / Dark Secret',
    tagline: 'Street racing heat with a deadly family tie.',
    poster: 'https://i.ytimg.com/vi/oRh7o397Jxw/hqdefault.jpg',
    badge: 'Racing',
    rating: '4.6',
  }
]
